services:
  dockhand:
    container_name: Dockhand
    image: fnsys/dockhand:${DOCKHAND_VERSION:-latest}
    ports:
      - 3000:3000
    networks:
      - public-apps
    environment:
      - DISABLE_LOCAL_LOGIN=${DOCKHAND_DISABLE_LOCAL_LOGIN:-False}
      - DISABLE_WHATS_NEW=${DOCKHAND_DISABLE_WHATS_NEW:-True}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - ${PATH_APPDATA:-/volume1/Docker/AppData}/dockhand:/app/data:rw
    labels:
      - "traefik.enable=${TRAEFIK_ENABLED:-false}"
      - "traefik.docker.network=public-apps"
      - "traefik.http.routers.dockhand-http.entrypoints=web"
      - "traefik.http.routers.dockhand-http.rule=Host(`dockhand.${TRAEFIK_CF_DNS_DOMAIN}`)"
      - "traefik.http.routers.dockhand-https.entrypoints=websecure"
      - "traefik.http.routers.dockhand-https.rule=Host(`dockhand.${TRAEFIK_CF_DNS_DOMAIN}`)"
      - "traefik.http.routers.dockhand-https.tls=true"
      - "traefik.http.routers.dockhand-https.tls.certresolver=cloudflare"
      - "traefik.http.routers.dockhand-https.tls.domains[0].main=${TRAEFIK_CF_DNS_DOMAIN}"
      - "traefik.http.routers.dockhand-https.tls.domains[0].sans=*.${TRAEFIK_CF_DNS_DOMAIN}"
      - "traefik.http.services.dockhand.loadbalancer.server.port=3000"
    restart: unless-stopped

networks:
  public-apps:
    external: true
