services:
  plex:
    container_name: plex
    hostname: Plex
    image: ghcr.io/linuxserver/plex:${PLEX_VERSION:-latest}
    user: ${PUID:-0}:${PGID:-0}
    security_opt:
      - no-new-privileges:true
    mem_limit: 8g
    cpu_shares: 1024
    privileged: true
    # ports:
    #  - 32400:32400
    network_mode: host
    environment: 
      - PUID=${PUID:-0}
      - PGID=${PGID:-0}
      - VERSION=public
      - PLEX_CLAIM=${PLEX_CLAIM_KEY:-''}
    devices:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - /dev/bus/usb:/dev/bus/usb            # Map host USB bus into the container
      - /dev/dri/renderD128:/dev/dri/renderD128
      - /dev/dri/card0:/dev/dri/card0
    volumes:
      - ${PATH_APPDATA}/plex/config:/config:rw
      - ${PATH_MEDIA}:/mnt/media/videos:rw
    labels:
      - "traefik.enable=${TRAEFIK_ENABLED}"
      - "traefik.docker.network=public-apps"
      - "traefik.http.routers.plex-https.entrypoints=websecure"
      - "traefik.http.routers.plex-https.rule=Host(`plex.${TRAEFIK_CF_DNS_DOMAIN:-''}`)"
      - "traefik.http.routers.plex-https.service=plex"
      - "traefik.http.routers.plex-https.tls=true"
      - "traefik.http.routers.plex-https.tls.certresolver=cloudflare"
      - "traefik.http.routers.plex-https.tls.domains[0].main=${TRAEFIK_CF_DNS_DOMAIN:-''}"
      - "traefik.http.routers.plex-https.tls.domains[0].sans=*.${TRAEFIK_CF_DNS_DOMAIN:-''}"
      - "traefik.http.services.plex.loadbalancer.serverstransport=insecure-transport@file"
      - "traefik.http.services.plex.loadbalancer.responseforwarding.flushinterval=100ms"
      - "traefik.http.services.plex.loadbalancer.server.url=https://<HostIpAddress>:32400"
      - "homepage.name=Plex"
      - "homepage.group=Media"
      - "homepage.icon=https://raw.githubusercontent.com/homarr-labs/dashboard-icons/refs/heads/main/svg/plex.svg"
      - "homepage.href=https://plex.${TRAEFIK_CF_DNS_DOMAIN:-''}"
      - "homepage.description=Media streaming platform"
    healthcheck:
      test: curl --connect-timeout 15 --silent --show-error --fail http://localhost:32400/identity
      interval: 1m00s
      timeout: 15s
      retries: 3
      start_period: 1m00s
    restart: unless-stopped
